version: '2'
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/zuidlaren
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    privileged: true
    volumes:
      - .:/zuidlaren
      - /home/websend/.config/pulse/cookie:/run/pulse/cookie
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - PULSE_SERVER=tcp:172.17.0.1:4713
      - PULSE_COOKIE=/run/pulse/cookie
    links:
     - db
     - redis
volumes:
  data: